# Default values for imaging-system.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

version: 2.18.1-31
neo4jReplicaCount: 1
serverReplicaCount: 1
etlReplicaCount: 1


serverservice:
  type: NodePort
  port: 30083

 
neo4jImage:
  name: castimaging/imagingneo4j
  tag: 2.18.1-31
  pullPolicy: IfNotPresent

serviceImage:
  name: castimaging/imagingservice
  tag: 2.18.1-31
  pullPolicy: IfNotPresent

etlImage:
  name: castimaging/imagingetl
  tag: 2.18.1-31
  pullPolicy: IfNotPresent


neo4jresources:
  limits:
    cpu: 4
    memory: 16G
  requests:
    cpu: 2
    memory: 8G
serviceresources:
  limits:
    cpu: 2500m
    memory: 2528Mi
  requests:
    cpu: 1000m
    memory: 1028Mi
etlresources:
  limits:
    cpu: 2500m
    memory: 3Gi
  requests:
    cpu: 1000m
    memory: 2000Mi


storageClassName:
  name: local-storage
