# Default values for imaging-system.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
version: 2.4.0
neo4jReplicaCount: 1
serverReplicaCount: 1
etlReplicaCount: 1

neo4jImage:
  name: castimaging/imagingneo4j
  tag:
  pullPolicy: IfNotPresent

serviceImage:
  name: castimaging/imagingservice
  tag:
  pullPolicy: IfNotPresent

etlImage:
  name: castimaging/imagingetl
  tag:
  pullPolicy: IfNotPresent

etlservice:
  type: NodePort
  port: 9001

neo4jresources:
  limits:
    cpu: 3
    memory: 4G
  requests:
    cpu: 3
    memory: 3G
serviceresources:
  limits:
    cpu: 2500m
    memory: 2528Mi
  requests:
    cpu: 1000m
    memory: 1028Mi
etlresources:
  limits:
    cpu: 500m
    memory: 528Mi
  requests:
    cpu: 100m
    memory: 128Mi
