apiVersion: v1
data:
  app.config: "{\n
      \"PORT\": \"9001\",\n
      \"NEO4J_BOLT_ENDPOINT\": \"neo4j.{{ .Release.Namespace }}.svc.cluster.local:7687\",\n
      \"NEO4J_USERNAME\": \"neo4j\",\n
      \"NEO4J_PASSWORD\": \"imaging\",\n
      \"TOKEN\": \"D5ED6A406775FC71B8D2A978883E8ED4\",\n
      \"NEO4J_IMPORT_PATH\": \"/opt/imaging/imaging-etl/upload/\",\n
      \"NEO4J_ARCHIVE_PATH\": \"/opt/imaging/imaging-etl/upload/archive/\",\n
      \"NEO4J_IMPORT_BATCH_SIZE\": \"1000\", \n
      \"LOG_PATH\": \"/opt/imaging/imaging-etl/logs/\",\n
      \"LOG_LEVEL\": \"debug\",\n
      \"HTTP_ENDPOINT\": \"http://server.{{ .Release.Namespace }}.svc.cluster.local:8084\"\n
      }\n"
kind: ConfigMap
metadata:
  name: etlconf
  namespace: {{ .Release.Namespace }}
