apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: etl
    version: {{.Values.etlImage.tag| default .Values.version}}
  name: etl
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.etlReplicaCount }}
  selector:
    matchLabels:
      app: etl
  template:
    metadata:
      labels:
        app: etl
    spec:
      containers:
        - image: "{{ .Values.etlImage.name }}:{{ .Values.etlImage.tag| default .Values.version}}"
          imagePullPolicy: "{{ .Values.etlImage.pullPolicy }}"
          command:
            - /bin/sh
            - -c
            - /opt/imaging/imaging-etl/imagingetl -CONFIG /opt/imaging/imaging-etl/config/app.config
          name: etl
          ports:
            - containerPort: 9001
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 9001
            initialDelaySeconds: 5
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 9001
            initialDelaySeconds: 3
            periodSeconds: 15
          resources:
            {{- toYaml .Values.etlresources | nindent 12 }}
          volumeMounts:
            - name: datadir
              mountPath: /opt/imaging/imaging-etl/upload
              readOnly: false
            - name: config
              mountPath: /opt/imaging/imaging-etl/config
            - name: logdir
              mountPath: /opt/imaging/imaging-etl/logs
              readOnly: false
      volumes:
        - name: config
          configMap:
            name: etlconf
        - name: datadir
          persistentVolumeClaim:
            claimName: importdir-neo4j-core-0
        - name: logdir
          persistentVolumeClaim:
            claimName: logdir-neo4j-core-0
