apiVersion: v1
data:
  application.properties: "# ========================================\n
    # List of the proxy config, split by comma\n#\n
    # make sure the root is unique and the elements in each params are matched\n
    proxy.config.roots=/etl/api,/api,/sourcecode/api,/neo4j/api\n
    proxy.config.targets=http://etl.{{ .Release.Namespace }}.svc.cluster.local:9001,http://localhost:9000,http://localhost:9980/api,http://neo4j.{{ .Release.Namespace }}.svc.cluster.local:7474\n
    proxy.config.token.names=token,token,token,token\n
    proxy.config.token.values=D5ED6A406775FC71B8D2A978883E8ED4,D5ED6A406775FC71B8D2A978883E8ED4,D5ED6A406775FC71B8D2A978883E8ED4,D5ED6A406775FC71B8D2A978883E8ED4 \n
    # ============================\n
    #JWT tokenValue configuration\n
    # ============================\n
    jwt.token.name=Authentication\n
    jwt.token.prefix=Bearer \n
    # make sure this key is secure enough\n
    jwt.token.sign.key=__my_super_secure_key__\n
    jwt.token.timeout.minutes=300\n
    refresh.token.name=refresh-token\n
    refresh.token.timeout.minutes=1200\n
    server.port=8084 \n
    #ssl must be enabled when enable saml mode\n
    server.ssl.enabled=false\n
    # =============================\n
    #
    Authentication parameters\n# -----------------------------\n
    # Applicable authentication
    configuration\n# -----------------------------\n#  - local\t->\tDefault. Contains
    a local definition of users and passwords\n
    #  - ldap\t->\tSet this configuration
    for authentication over LDAP(S)\n#  - ad\t->\tSet this configuration for authentication
    over LDAP(S) with basic Active Directory instances (simplified mode)\n#  - saml
    -> Set this configuration for SSO authentication using SAML\nsecurity.mode=local\n
    spring.datasource.url=jdbc:h2:file:./db/loginservice;AUTO_SERVER=TRUE\n
    spring.datasource.username=sa\n
    spring.datasource.password=\n
    spring.datasource.driver-class-name=org.h2.Driver\n
    spring.jpa.database-platform=org.hibernate.dialect.H2Dialect\n
    spring.jpa.hibernate.ddl-auto=none\n
    spring.h2.console.enabled=false\n
    spring.h2.console.path=/h2\n
    spring.liquibase.change-log=classpath:db/changelog/changelog.xml\n
    #-----------------------------\n
    # Authentication Configuration folder location\n#
    -----------------------------\n
    security.config.folder=security\n# security.config.folder=src/main/resources/security\n#
    -----------------------------\n
    # Parameters for ldap mode\n# -----------------------------\n#
    security.ldap.url=\n# security.ldap.account.dn=\n
    # security.ldap.account.password=\n#
    security.ldap.usersearch.base=\n
    # security.ldap.usersearch.filter=\n
    # security.ldap.groupsearch.base=\n#
    security.ldap.groupsearch.filter=\n# security.ldap.groupsearch.base.filter=\nsecurity.ldap.url=ldap://corp.castsoftware.com\nsecurity.ldap.account.dn=casta1\nsecurity.ldap.account.password=CRYPTED2:0F22B065057ABD0DDEFC97DFC3ED5BDB\nsecurity.ldap.usersearch.base=DC=corp,DC=castsoftware,DC=com\nsecurity.ldap.usersearch.filter=(&(objectClass=user)(sAMAccountName={0}))\nsecurity.ldap.groupsearch.base=DC=corp,DC=castsoftware,DC=com\nsecurity.ldap.groupsearch.filter=(&(objectClass=group)(member:1.2.840.113556.1.4.1941:={0}))\nsecurity.ldap.groupsearch.base.filter=(&(objectClass=group)(name={0}))\nsecurity.ldap.groupsearch.maxSearchDepth=1\n#security.ldap.url=\n#security.ldap.account.dn=\n#security.ldap.account.password=\n#security.ldap.usersearch.base=\n#security.ldap.usersearch.filter=(&(objectClass=user)(sAMAccountName={0}))\n#security.ldap.groupsearch.base=\n#security.ldap.groupsearch.filter=(&(objectClass=group)(member={0}))\n#security.ldap.groupsearch.base.filter=(&(objectClass=group)(name={0}))\n#
    security.ldap.groupsearch.maxSearchDepth=10\n
    # Performance fix for nested groups
    on AD\n#security.ldap.groupsearch.filter=(&(objectClass=group)(member:1.2.840.113556.1.4.1941:={0}))\n
    #security.ldap.groupsearch.maxSearchDepth=1\n
    #-----------------------------\n
    # Parameters for ad mode\n
    # -----------------------------\n
    security.ad.url=\nsecurity.ad.domain=\n#
    ==============\n# Parameters for saml mode\n# --------------\n
    # Specify the location
    for the metadata source\n
    # By default, it uses a file on the filesystem and must
    be given an absolute path\n
    # You can specify a Http resource by providing a full
    url to a metadata f\n\n\n# or a classpath resource using \"classpath:myMetadataFile.xml\"
    for example\n# NB : when using an HTTPS metadata source, you must first add the
    public certificate to the keystore\nsecurity.saml.metadata.source=\n
    # Specifythe filename of the keystore to use for the SAML certificates\n
    # The file must
    be placed inside the security.config.folder\n
    security.saml.keystore.filename=\n
    #Specify the default alias in the keystore for the certificate\n
    security.saml.keystore.default-alias=\n
    #Specify the keystore and alias password\n
    security.saml.keystore.password=\n# The
    XML attribute containing the user's name\n
    # If this attribute is missing or empty,
    the user ID will be used\nsecurity.saml.attribute.username=\n
    # The XML attribute
    containing the user's group in the SAML response\n
    security.saml.attribute.group=\n#
    -------------------------------------------------------------\n
    #  ssl configuration,
    ssl is required when enable the saml mode\n
    # -------------------------------------------------------------\n
    #The format used for the keystore. It could be set to JKS in case it is a JKS file\n
    server.ssl.key-store-type=\n
    #The path to the keystore containing the certificate\nserver.ssl.key-store=\n
    #The password used to generate the certificate\n
    server.ssl.key-store-password=\n
    #The alias mapped to the certificate\nserver.ssl.key-alias=\n
    # -------------------------------------------------------------\n
    #log configuration\n
    # -------------------------------------------------------------\n
    logging.level.root=info\nlogging.level.com.castsoftware.aip.console.security=debug\n
    logging.path=/opt/imaging/imaging-service/logs\n
    logging.file=${logging.path}/login.log\n
    logging.file.max-size=5MB\n
    #-------------------------------------------------------------\n
    #  audit trail log file location\n
    # -------------------------------------------------------------\n
    audit.trail.file=${logging.path}/audit-trail.log\n"
kind: ConfigMap
metadata:
  name: loginconf
  namespace: {{.Release.Namespace}}
