apiVersion: "apps/v1"
kind: StatefulSet
metadata:
  name: neo4j-core
  namespace: {{.Release.Namespace}}
spec:
  serviceName: neo4j
  replicas: {{.Values.neo4jReplicaCount}}
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
        component: core
    spec:
      containers:
        - name: neo4j
          image: "{{.Values.neo4jImage.name}}:{{.Values.neo4jImage.tag}}"
          imagePullPolicy: "{{.Values.neo4jImage.pullPolicy}}"
          command:
            - /bin/sh
            - -c
            - mkdir /var/lib/neo4j/import/csv;cp /opt/config/neo4j.conf /var/lib/neo4j/conf/;unzip -nq /var/lib/neo4j/plugins/packagereference.zip -d /var/lib/neo4j/import;neo4j-admin restore --verbose --from=/var/lib/neo4j/import/packagereference --database=packagereference --force --move;neo4j-admin set-initial-password imaging;neo4j console
          env:
            - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
              value: "yes"
          ports:
            - containerPort: 7474
              name: browser
            - containerPort: 7687
              name: bolt
            - containerPort: 6362
              name: backup
          securityContext:
            privileged: true
          volumeMounts:
            - name: datadir
              mountPath: "/data"
            - name: importdir
              mountPath: "/var/lib/neo4j/import"
            - name: logdir
              mountPath: "/var/lib/neo4j/logs"
            - name: conf
              mountPath: "/opt/config"
      volumes:
        - name: conf
          configMap:
            name: neo4jconfig
            defaultMode: 0777
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: standard
        resources:
          requests:
            storage: "16Gi"
    - metadata:
        name: importdir
      spec:
        accessModes:
          - ReadWriteMany
        storageClassName: standard
        resources:
          requests:
            storage: "2Gi"
    - metadata:
        name: logdir
      spec:
        accessModes:
          - ReadWriteMany
        storageClassName: standard
        resources:
          requests:
            storage: "2Gi"
