---
kind: Service
apiVersion: v1
metadata:
  name: server
  labels:
    app: server
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: login
      port: 8084
      targetPort: 8084  
  selector:
    app: server
  type: NodePort
