apiVersion: v1
data:
  application.properties: |
    server.port=9980
    server.max-http-header-size=40KB
    api.token=D5ED6A406775FC71B8D2A978883E8ED4
    datasource.url=
    datasource.username=
    datasource.password=
    datasource.alias=
    datasource.min.idle=1
    datasource.max.pool.size=1
    logging.level.root=info
    logging.level.com.castsoftware.aip.console.sourcecodeexplorer.service=debug
    logging.path=/opt/imaging/imaging-service/logs
    logging.file.name=${logging.path}/sourcecode.log
    logging.file.max-size=5MB
    trace.methods.duration=false
    trace.methods.result=false
    trace.queries.duration=false
    trace.queries.shrink=true
    trace.indented=true

kind: ConfigMap
metadata:
  name: sourcecodeconf
  namespace: {{ .Release.Namespace }}
